graph TD;
    Start_Menu-->Deal_Cards;
    Deal_Cards-->Add_To_Crib;
    Add_To_Crib-->Play;
    Play-->Wait;
    Wait-->Play;
    Wait-->Calculate_Score;
    Play-->Calculate_Score;
    Calculate_Score-->Deal_Cards;


