graph TD;
    Start_Menu-->Pick_Card;
    Pick_Card-->Add_To_Crib;
    Add_To_Crib-->Cut_Deck;
    Cut_Deck-->Play
    Play-->Wait;
    Wait-->Play;
    Wait-->Calculate_Score;
    Play-->Calculate_Score;
    Calculate_Score-->Add_To_Crib;


